<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.8">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.5" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../AiMeetingAssistant.Application/AiMeetingAssistant.Application.csproj" />
    <ProjectReference Include="../AiMeetingAssistant.Domain/AiMeetingAssistant.Domain.csproj" />
  </ItemGroup>
</Project>
